/*
 *
 * Register constants
 *
 */

export const DEFAULT_ACTION = 'app/Register/DEFAULT_ACTION';
export const REGISTER_PAGE_INIT = 'app/Register/REGISTER_PAGE_INIT';
export const REGISTER_PAGE_CHANGE_NAME =
  'app/Register/REGISTER_PAGE_CHANGE_NAME';
export const REGISTER_PAGE_CHANGE_EMAIL =
  'app/Register/REGISTER_PAGE_CHANGE_EMAIL';
export const REGISTER_PAGE_CHANGE_PASSWORD =
  'app/Register/REGISTER_PAGE_CHANGE_PASSWORD';
export const REGISTER_PAGE_CHANGE_ORG_NAME =
  'app/Register/REGISTER_PAGE_CHANGE_ORG_NAME';
export const REGISTER_USER_SUCCESS = 'app/Register/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'app/Register/REGISTER_USER_FAILURE';
export const REGISTER_PAGE_SHOW_LOADING =
  'app/Register/REGISTER_PAGE_SHOW_LOADING';
export const REGISTER_VALIDATION_ERROR =
  'app/Register/REGISTER_VALIDATION_ERROR';
export const REGISTER_TOOGLE_EMAIL_VERIFY =
  'app/Register/REGISTER_TOOGLE_EMAIL_VERIFY';
export const REGISTER_PAGE_CHANGE_EMAIL_CODE =
  'app/Register/REGISTER_PAGE_CHANGE_EMAIL_CODE';
export const REGISTER_PAGE_DISABLE_RESEND_CODE =
  'app/Register/REGISTER_PAGE_DISABLE_RESEND_CODE';
